disabled_rules:
- line_length
- trailing_whitespace
- leading_whitespace
- force_try
- function_body_length
included:
excluded:
- Pods
- RespectU/Supporting Files/ERProgressHud.swift

cyclomatic_complexity: 20
identifier_name:
    excluded:
    - id
    - ce
    - bs
    - xb
    - tb
    - fx
    - CE
    - BS
    - s
    - a
    - b
    - c
type_name:
    excluded:
    - CE
    - BS
trailing_space:
    
