disabled_rules:
  - line_length
  - trailing_whitespace
  - leading_whitespace
  - force_try
  - function_body_length

excluded:
  - Pods
  - RespectU/Resources/SwiftGen

cyclomatic_complexity: 20

identifier_name:
    excluded:
    - id
    - ce
    - bs
    - xb
    - tb
    - fx
    - CE
    - BS
    - s
    - a
    - b
    - c

type_name:
    excluded:
    - CE
    - BS

line_length:
  warning: 99
  error: 120
